### ISSUE TITLE
Impossible Create and Edit Widget Selector e HTML

### ISSUE THREAD

**Issue by gmtittarelli** [KnowageLabs/Knowage-Server#125]
Salve/Hi,
After install Knowage the widget Select and HTML are blank and not editable, under the screen shot of error.
Thank's

Italiano
ho appena installato per la terza volta KnowAge su una macchina Windows 10 64 bit.
Riporto il file della versione e la finestra firefox in cui cerco di aprire in edit il widget Selectot (Stessa cosa per HTML) ma non succede nulla.
Gli altri widget funzionano correttamente solo questi due non vanno in edit.
Spero possiate aiutarmi a capire il problema

GRAZIE

![VERSION](https://user-images.githubusercontent.com/63389296/78863522-14919b00-7a3a-11ea-8aa3-d4ec451dc4cf.png)
![FIREFOX](https://user-images.githubusercontent.com/63389296/78863525-15c2c800-7a3a-11ea-8f23-0d0a28b812e7.png)
![VERSION](https://user-images.githubusercontent.com/63389296/78863537-1e1b0300-7a3a-11ea-9198-15d9b48befcc.png)
![FIREFOX](https://user-images.githubusercontent.com/63389296/78863538-1eb39980-7a3a-11ea-94d8-3ed9fafe4403.png)

**Comment by kerny3d** [comment]
@gmtittarelli, it's a software error caused by the missing of the call to `$sce.trustAsResourceUrl(value)` when we load the widget templates. The fix needs to be done in `htmlWidget.js` and `selectorWidget.js` in the method `$scope.getTemplateUrl()`: you are free to make a pull request about that or just wait the fix from us in the next few days.

@gmtittarelli, è un errore software dovuto alla mancanza della chiamata `$sce.trustAsResourceUrl(value)` quando carichiamo le template delle widget. La modifica interessa il metodo `$scope.getTemplateUrl()` nei file `htmlWidget.js` e `selectorWidget.js`: puoi fare una pull request oppure attendere la risoluzione da parte nostra che scheduleremo nei prossimi giorni.

**Comment by gmtittarelli** [comment]
Ok.
Thank's

**Comment by gmtittarelli** [comment]
I wanted to know where I need to look on your site to get the update to the indicated problem and maybe where to download a guide to update or fix the bug.
Creating dashboards without the Selector remains really difficult.
Thank you

Volevo sapere dove devo guardare sul vostro sito per avere l'aggiornamento al problema indicato e magari dove scaricare una guida per effettuare l'aggiornamento o il fix del bug.
Creare cruscotti senza il Selector resta davvero difficile.
Grazie

**Comment by gmtittarelli** [comment]
@kerny3d i'm sorry the fix are ready? Without selector :(
Thank's

**Comment by gmtittarelli** [comment]
The bug is into config file. With localhost the widget not working.
I must change localhost with my ip address.
