### ISSUE TITLE
Connect Knowage to  KeyCloak

### ISSUE THREAD

**Issue by ouadhi** [KnowageLabs/Knowage-Server#170]
how to authorize keycloak to manage authorization and access to knowage

**Comment by jdbranham** [comment]
I had the same requirement.  
The existing OAuth2 classes don't support Keycloak because it communicates with the FIWare app for configuration.   

I ended up creating some generic OAuth classes and got it working with keycloak.  

See here for full docker example -  
https://github.com/savantly-net/knowage-docker

Also, the source code for the OAuth2 classes are available here -  
https://github.com/savantly-net/Knowage-Server/tree/jb/oauth2/knowageoauth2

High praise to the Knowage developers - I see there are lots of best practices at work here.  
Even though the public documentation is lacking for development, I was able to quickly build and extend the Knowage platform.
