### ISSUE TITLE
REST data set : parameters are not substituted in request URL  

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server#223]
**Describe the bug**

following the fix of #222, we tested the propagation of parameter values for a REST data set, if the substitution is done OK for the content, it is not applied for the parameters in the request URL.

**To Reproduce**

1. create a REST data set, 
1. add a parameter "par_test", of type string or whatever
1. use it in request URL, such as get `http://<host>:<port>/<path>?param=$P{par_test}`
2. preview the data set, set a value for the parameter
1. check that the request is sent but without substitution of `$P{par_test}` with the given value (we checked with nodered and an http_in + debug)

**Expected behavior**
the $P{par_test} should be substituted by the given value in the request URL !

**Comment by agaldemas** [comment]
Hi @kerny3d, Sorry typo updated !

**Comment by agaldemas** [comment]
Just to share with my colleague @HugoT852 !

**Comment by kerny3d** [comment]
Ok, I didn't replicate your case. I've run a simple API REST with Node in my local environment and using and URL like `http://127.0.0.1:3000/page=$P{page}` and a parameter called `page` everything works fine:
![image](https://user-images.githubusercontent.com/6751879/129181970-c35af166-1094-4a35-a4f6-508c0eaad9c1.png)
![image](https://user-images.githubusercontent.com/6751879/129182012-0da4479f-3069-4d25-9b73-e664ce7098b1.png)

I've found a little problem on requests with empty body (see the commit [ac89688](https://github.com/KnowageLabs/Knowage-Server/commit/ac89688e021e8039f474c95d6c5b39dd506735cf)).

You told me the expected behavior but I need you to be more precise on the actual one: does the request happens just fine except for the parameter replacement? Do you see errors or very strange behaviors? Do you see some data if you replace the parameter value with a constant one?

**Comment by agaldemas** [comment]
Hi @kerny3d,

The request happens just fine except for the parameter replacement, and an empty body...

We'll test again with the new commit and come back to you ! (@HugoT852 pls to make a test tomorrow)

**Comment by agaldemas** [comment]
Hello, @kerny3d, sorry for silence, we tested with the commit ac89688

It is OK for parameter substitution in the request only !

My new question is: 

does this fix will it be merged in the 7.4.5, 7.4.8 or the awaited 8.0 ?

this because we absolutely need this to work, to achieve our project, so it's more than a question...;O)

Thanks in advance for your kind answer

**Comment by kerny3d** [comment]
Hi @agaldemas, we'll release the 7.4.9 soon: we're packaging all the bug fixes in it.

**Comment by agaldemas** [comment]
Thanks for the update @kerny3d, we'll check daily the releases on dockerhub !

**Comment by kerny3d** [comment]
7.4.9 released:

https://hub.docker.com/layers/knowagelabs/knowage-server-docker/7.4.9/images/sha256-374185f137e1fb13fa8f0a1b524670b1d3cb1da9f9f53ab1c0743a3db4767549?context=explore
